# Generated by Django 6.0.3 on 2026-03-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume gen')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🎵', max_length=50, verbose_name='Icon emoji')),
            ],
            options={
                'verbose_name': 'Gen muzical',
                'verbose_name_plural': 'Genuri muzicale',
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Stare/Mood')),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#7c3aed', max_length=20, verbose_name='Culoare hex')),
            ],
            options={
                'verbose_name': 'Mood',
                'verbose_name_plural': 'Mood-uri',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu melodie')),
                ('artist', models.CharField(max_length=200, verbose_name='Artist / Compozitor')),
                ('audio_file', models.FileField(upload_to='songs/', verbose_name='Fișier audio (MP3/WAV)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Copertă')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Durată (secunde)')),
                ('bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Recomandat')),
                ('plays_count', models.PositiveIntegerField(default=0, verbose_name='Redări')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre', verbose_name='Gen')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.mood', verbose_name='Mood')),
            ],
            options={
                'verbose_name': 'Melodie',
                'verbose_name_plural': 'Melodii',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume playlist')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlists/')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('songs', models.ManyToManyField(blank=True, to='music.song', verbose_name='Melodii')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlist-uri',
            },
        ),
    ]
