# Generated by Django 6.0.3 on 2026-03-29 09:41

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='songs/', validators=[music.models.validate_audio_file], verbose_name='Fișier audio (MP3/WAV)'),
        ),
    ]
