# Generated by Django 6.0.3 on 2026-04-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('business', models.CharField(blank=True, max_length=200, verbose_name='Tip locație')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Citit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mesaj contact',
                'verbose_name_plural': 'Mesaje contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
