# Generated by Django 6.0.3 on 2026-04-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_order_representative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Denumire firmă')),
                ('company_cui', models.CharField(blank=True, max_length=20, verbose_name='CUI')),
                ('company_reg', models.CharField(blank=True, max_length=50, verbose_name='Nr. Reg. Comerț')),
                ('company_address', models.CharField(blank=True, max_length=300, verbose_name='Adresa firmei')),
                ('brand_name', models.CharField(blank=True, max_length=200, verbose_name='Brand / Locație')),
                ('venue_address', models.CharField(blank=True, max_length=300, verbose_name='Adresa locației')),
                ('business_type', models.CharField(choices=[('cafenea', 'Cafenea / Cofetărie'), ('restaurant', 'Restaurant / Pizzerie'), ('bar', 'Bar / Pub'), ('club', 'Club / Discotecă'), ('hotel', 'Hotel / Pensiune'), ('salon', 'Salon / Spa'), ('retail', 'Magazine / Retail'), ('birou', 'Birou / Coworking'), ('cabinet', 'Cabinet / Clinică'), ('gym', 'Gym / Fitness')], default='cafenea', max_length=20, verbose_name='Tip afacere')),
                ('business_size', models.CharField(choices=[('< 100 mp', '< 100 mp'), ('101-250 mp', '101-250 mp'), ('251-500 mp', '251-500 mp'), ('501-1000 mp', '501-1000 mp'), ('> 1000 mp', '> 1000 mp')], default='< 100 mp', max_length=20, verbose_name='Suprafață')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Persoană de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('new', '🆕 Nou'), ('contacted', '📞 Contactat'), ('interested', '👍 Interesat'), ('proposal_sent', '📄 Ofertă trimisă'), ('won', '✅ Câștigat'), ('lost', '❌ Pierdut')], default='new', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('referral', 'Recomandare'), ('google', 'Google'), ('facebook', 'Facebook'), ('walk_in', 'Vizită fizică'), ('cold_call', 'Cold call'), ('other', 'Altul')], default='other', max_length=20, verbose_name='Sursă')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('next_followup', models.DateField(blank=True, null=True, verbose_name='Următorul follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Asignat')),
                ('converted_to_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='music.order', verbose_name='Comandă rezultată')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Lead-uri',
                'ordering': ['-updated_at'],
            },
        ),
    ]
