# Generated by Django 6.0.3 on 2026-04-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0009_userprofile_plain_password"),
        ("music", "0012_order_venue_address_alter_order_plan"),
    ]

    operations = []
