# Generated by Django 6.0.3 on 2026-04-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0011_order_representative"),
        ("music", "0014_merge_20260410_1209"),
    ]

    operations = []
