# Generated by Django 6.0.3 on 2026-04-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0014_merge_crm"),
        ("music", "0015_merge_20260421_1718"),
    ]

    operations = []
